extern crate cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_parse_include(&["nalgebra"])
        .with_parse_deps(true)
        .with_cpp_compat(true)
        .with_language(cbindgen::Language::C)
        .with_autogen_warning(
            "/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */",
        )
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("viam_rust_utils.h"); // Output to target directory
}
