extern crate cbindgen;

use std::{collections::HashMap, env};

use cbindgen::{Config, ExportConfig, FunctionConfig, ParseConfig, RenameRule, StructConfig};

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    // mangled nalgebra type outputs, mapped to a prefixed snake case variant
    let nalgebra_types = vec![
        ("ArrayStorage_f64__3__1", "nalgebra_array_storage_f64__3__1"),
        (
            "Matrix_f64__u3__u1__array_storage_f64_3_1",
            "nalgebra_matrix_f64_3_1",
        ),
        ("Vector3_f64", "nalgebra_vector3_f64"),
        ("ArrayStorage_f64__4__1", "nalgebra_array_storage_f64__4__1"),
        (
            "Matrix_f64__u4__u1__array_storage_f64_4_1",
            "nalgebra_matrix_f64_4_1",
        ),
        ("Vector4_f64", "nalgebra_vector4_f64"),
        ("Quaternion_f64", "nalgebra_quaternion_f64"),
        (
            "Unit_matrix_f64_u3_u1_array_storage_f64_3_1",
            "nalgebra_unit_matrix_f64_3_1",
        ),
        ("UnitVector3_f64", "nalgebra_unit_vector3_f64"),
        ("Rotation_f64__3", "nalgebra_rotation_f64_3"),
    ];

    // mangled viam type outputs, mapped to a prefixed snake case variant
    let viam_types = vec![
        (
            "Matrix_f64__const_3__const_3__array_storage_f64_3_3",
            "nalgebra_matrix_f64_3_3",
        ),
        ("ArrayStorage_f64__3__3", "nalgebra_array_storage_f64__3__3"),
        ("SMatrix_f64__3__3", "nalgebra_smatrix_f64_3_3"),
        ("Rotation_f64__3", "nalgebra_rotation_f64_3"),
        ("Rotation3_f64", "nalgebra_rotation3_f64"),
        ("DialFfi", "viam_dial_ffi"),
        ("AxisAngle", "viam_axis_angle"),
        ("EulerAngles", "viam_euler_angles"),
        ("OrientationVector", "viam_orientation_vector"),
    ];

    let rename = vec![nalgebra_types, viam_types]
        .into_iter()
        .flatten()
        .map(|(a, b)| (a.to_string(), b.to_string()))
        .collect::<HashMap<String, String>>();

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(Config {
            parse: ParseConfig {
                parse_deps: true,
                include: Some(vec!["nalgebra".to_string()]),
                ..Default::default()
            },
            export: ExportConfig {
                rename,
                ..Default::default()
            },
            structure: StructConfig {
                rename_associated_constant: RenameRule::SnakeCase,
                rename_fields: RenameRule::SnakeCase,
                ..Default::default()
            },
            function: FunctionConfig {
                deprecated: Some(
                    "/// @deprecated please use `viam_`-prefixed function instead".to_string(),
                ),
                ..Default::default()
            },
            ..Default::default()
        })
        .with_cpp_compat(true)
        .with_language(cbindgen::Language::C)
        .with_autogen_warning(
            "/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */",
        )
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("viam_rust_utils.h"); // Output to target directory
}
