name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version of the crate. You can specify a version or a bump type (major/minor/patch)'
        type: string
        required: true

jobs:
  prepare:
    if: github.repository_owner == 'viamrobotics' && github.ref == 'refs/heads/main' && contains(fromJson('["njooma"]'), github.actor)
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64
    outputs:
      sha: ${{ steps.commit.outputs.commit_long_sha }}
      version: ${{ steps.bump_version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_READ_TOKEN }}

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: install cargo-bump

      - name: Bump Version
        id: bump_version
        uses: actions-rs/cargo@v1
        with:
          command: bump ${{ inputs.version }}

      - name: Output version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "cargo metadata --format-version=1 --quiet --no-deps | jq '. | .packages | .[0].version'"

      - name: Commit + Push
        id: commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          default_author: github_actions
          message: Bumping version to v${{ env.SDK_VERSION }} [skip ci]

  build:
    if: github.repository_owner == 'viamrobotics' && github.ref == 'refs/heads/main' && contains(fromJson('["njooma"]'), github.actor)
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64
    uses: viamrobotics/rust-utils/.github/workflows/build_binaries.yml@main

  release:
    needs: [prepare, build]
    if: github.repository_owner == 'viamrobotics' && github.ref == 'refs/heads/main'
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64

    steps:
      - uses: actions/download-artifact@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.prepare.outputs.version }}
          files: dist/*
          draft: true
          prerelease: ${{ contains(inputs.version, 'pre') }}
          fail_on_unmatched_files: true
